### ISSUE TITLE
Exception: Instruction expected at:14

### ISSUE THREAD

**Issue by min23asdw** [RiwEZ/261304-AssemblySim#12]
![image](https://user-images.githubusercontent.com/76154445/195687294-c9a54673-da77-4ad0-bd25-ee514a074267.png)

        lw 0 5 sstack   // stack = 30
        lw 0 6 one    //$(6) = 1
        lw 0 4 neq1 //&(4)  = -1
        addrfn     lw 5 1 0   // &(1) = #5[0]  .30
        lw 5 2 1   // $(2) = #5[1]  .31
        beq  1 2 jif   //if(n==r)  2if:
        beq  2 0 jif   //if(r==0)  2if: 
        add 1 4 1 // n-1
        add 5 6 5     // push stack
        add 5 6 5    // 5 += 2
        sw  5 1 0  // $(1) ->  #32
        sw  5 2 1  // $(2) ->  #33
        jalr 7 7
		beq 0 0 callfn
        add 2 4 2 // n-1
        add 5 6 5     // push stack
        add 5 6 5    // 5 += 2
        sw  5 1 0  // $(1) ->  #32
        sw  5 2 1  // $(2) ->  #33        
        jalr 7 7           
		beq 0 0 callfn
       beq 0 0 done               
       jif add 3 6 3         // return 1 (+1) // 3 += 1
       add 5 4 5     // pop stack
       add 5 4 5    // 5 += 2 
       add 0 7 6    // return pc+1
       beq 0 0 7    // back
       done    halt                        //end of program
       sstack .fill n 
       n .fill 3
       r .fill 2
       one    .fill  1
       neq1 .fill -1
       callfn  .fill   addrfn            //will contain the address of start

**Comment by PutawanDE** [comment]
Fix with 5f60308b1d80cf5921ebad816d137874708e5f1e. On line 14, in front of beq is a tab character `\t`, now it is supported.
