### ISSUE TITLE
hello reg 0  must be alway ZERO

### ISSUE THREAD

**Issue by min23asdw** [RiwEZ/261304-AssemblySim#15]
![image](https://user-images.githubusercontent.com/76154445/195703522-6541214e-6160-471f-9936-dd54686485a4.png)

**Comment by min23asdw** [comment]
![image](https://user-images.githubusercontent.com/76154445/195703650-ddb234b2-b5ad-4269-a80c-48d757058e78.png)
จะใช้ reg 0 เป็น ถังขยะเฉยๆ

**Comment by PutawanDE** [comment]
Fix with 2567ea826a71b474198e064c318d3958cfe2ffad
