### ISSUE TITLE
No exception when label is number

### ISSUE THREAD

**Issue by Bug-Too** [RiwEZ/261304-AssemblySim#2]
Label should not be number and instruction should except when argument not match

test case
``` python
1 add 0 1  label should not be number
1 add 0
```
result:
![image](https://user-images.githubusercontent.com/72825738/194920355-e93eb8a5-fbd1-4f44-bc8a-d325b29ff92a.png)

**Comment by RiwEZ** [comment]
on commit 1b0336724e5fbf0c49b45293623b269592c1b1de, this should be fixed already.
