### ISSUE TITLE
Exception should not rise when there is no label

### ISSUE THREAD

**Issue by Bug-Too** [RiwEZ/261304-AssemblySim#3]
Instruction expected rise when there is no label

test/t5.s
``` python
.fill 55
```
result:
![image](https://user-images.githubusercontent.com/72825738/194920760-32c0f5b0-1fe4-467d-8c23-deb66e989229.png)

**Comment by RiwEZ** [comment]
on commit 1b0336724e5fbf0c49b45293623b269592c1b1de, this should be fixed already.
