### ISSUE TITLE
Fill should be able to get label

### ISSUE THREAD

**Issue by Bug-Too** [RiwEZ/261304-AssemblySim#4]
Error should not be rise and .fill should be able to get label

test case tests/t5.s
``` python
start add 0 0 0
x .fill add
```
result:
![image](https://user-images.githubusercontent.com/72825738/194924333-2cd174c3-192f-49d2-80d2-345b0610d2fa.png)

**Comment by RiwEZ** [comment]
on commit 1b0336724e5fbf0c49b45293623b269592c1b1de, this should be fixed already.
